services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - open-webui:/app/backend/data
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
    networks:
      - llmops-network

  gradio-app:
    build: .
    container_name: gradio-app
    restart: unless-stopped
    ports:
      - "7861:7860"
    env_file:
      - .env
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
    networks:
      - llmops-network

volumes:
  open-webui:

networks:
  llmops-network:
    external: true